### ISSUE TITLE
While creating a custom app, Basic details>> Is there a convention between Name and ID ?

### ISSUE THREAD

**Issue by deepak-dassana** [dassana-io/web-components#732]
**Steps to reproduce:**

- Create a Custom App

- In the Basic details page, enter Name and ID autofills with "_" prepended.

- Edit the ID and Name doesn't change accordingly. 

**Query:** Is there a convention between Name and ID ?![Screenshot 2022-09-07 at 1.03.26 PM.png](https://images.zenhubusercontent.com/63105f664753f36c1fa0868e/ea0ff1de-a048-48e9-9496-0fcfca7ffb94)

**Comment by parth-dassana** [comment]
name is converted to id but not the other way around
